### ISSUE TITLE
Force reboot on j530

### ISSUE THREAD

**Issue by kegang0619** [SPART4NICUS/DOWNLOADS#4]
Android ver: 9, one ui 1.1

Hi, I recently updated to kraken rc15, and I found that my phone was forced to reboot whenever I turned on the screen. So I re-flashed Rc14, and the problem has disappeared.

**Comment by at644** [comment]
Same problem on my J600f running havoc 2.9. Thought this was due to the treble vendor bug

**Comment by SPART4NICUS** [comment]
yeah working on it, it's a deep sleep issue.

**Comment by at644** [comment]
Thanks bro. And can u plz add a frequency between 1.79 and 1.92 since the new clock speed always results in a force reboot.

**Comment by yagoplx** [comment]
Can confirm that 1.92GHz makes my SM-J730F crash.

Even without it the kernel is crazy butter-smooth still. Thus, maybe keep the OC there for gamers but at a lower frequency that does not cause the system to crash.

**Comment by yagoplx** [comment]
Or, perhaps completely get rid of OC or make it very gentle, as this has been an issue before:
https://github.com/SPART4NICUS/DOWNLOADS/issues/1#issue-513842841

**Comment by SPART4NICUS** [comment]
fixed, move to AresKernel builds
