### ISSUE TITLE
Hotplug on exynos 7870

### ISSUE THREAD

**Issue by yagoplx** [SPART4NICUS/DOWNLOADS#5]
While messing around with the J7 on kernel manager software I noticed that unlike Qualcomm-equipped phones here there's no hotplug tab. Yet, the cores can still be individually disabled manually. Is this purely visual or incurs no energy saving benefits on Exynos?

Furthermore, if there is in fact hotplugging on Exynos (and a benefit to it), is there a way to enable it on your kernel?

**Comment by SPART4NICUS** [comment]
nah I nuked the hotplug, it caused slow downs and it doesn't really save any power at all
